### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str

### ISSUE THREAD

**Issue by AESPS** [sjhilt/GasPot#11] opened 2022-06-23 15:12 UTC
i get this error when trying to insert ^AI20100 command

Unknown Error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "GasPot1.py", line 302, in <module>
    while not ('\n' in response or '00' in response):
TypeError: a bytes-like object is required, not 'str'

**Comment by sjhilt** [comment] 2022-06-23 19:46
Hi I haven't worked with this code for a while I think its something with Python3 and doesn't work as intended and I'll eventually get around to fixing it. But for now I suggest you use the GasPot that is built in ConPot. https://github.com/mushorg/conpot

**Comment by sjhilt** [comment] 2023-01-26 19:09
Closed it due to repo being not updated and conpot still works.

**Closed as completed** 2023-01-26 19:09 UTC
